config/routes.rb
Spree::Core::Engine.routes.prepend do
  namespace :admin do
    resources :article_categories
    resources :articles
  end

  resources :articles
end

app/models/spree/article.rb
class Spree::Article < ActiveRecord::Base
  belongs_to :article_category
  has_one :language
  has_many :article_products
  has_many :products, :through => :article_products

  validates_presence_of :name, :content, :article_category_id
  validates_numericality_of :article_category_id

  # Bepaalt of deze article relevant is voor het meegegeven product.
  def is_relevant_for_product?(product)
    self.products.include?(product)
  end
end

app/models/spree/article_category.rb
class Spree::ArticleCategory < ActiveRecord::Base
  has_attached_file :icon, :styles => { :mini => ["48x48#", :png] }
  has_many :articles

  validates_presence_of :name
  validates_attachment_presence :icon, :on => :create
  validates_length_of :name, :maximum => 100

end

app/models/spree/article_product.rb
class Spree::ArticleProduct < ActiveRecord::Base
  validates_presence_of :product_id, :article_id
  belongs_to :product
  belongs_to :article
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_many :article_products
  has_many :articles, :through => :article_products
end

app/controllers/spree/admin/article_categories_controller.rb
# Controller voor het toevoegen van articlecategorieen. Deze controller maakt geen gebruik van Ajax functionaliteiten,
# omdat Javascript geen toegang heeft tot lokale bestanden en het daarom onmogelijk is om via een remote form bestanden
# te uploaden.
class Spree::Admin::ArticleCategoriesController < Spree::Admin::ResourceController

  def index
    @article_categories = Spree::ArticleCategory.all
  end

  def new
    @article_category = Spree::ArticleCategory.new
  end

  def edit
    @article_category = Spree::ArticleCategory.find(params[:id])
  end

  def create
    @article_category = Spree::ArticleCategory.new(params[:article_category])

    if @article_category.save
      flash.now[:notice] = t('admin.article_categories.form.created')
      redirect_to :action => :index
    else
      respond_with @article_category
    end
  end

  def update
    @article_category = Spree::ArticleCategory.find(params[:id])

    if @article_category.update_attributes(params[:article_category])
      flash.now[:notice] = t('admin.article_categories.form.updated')
      redirect_to :action => :index
    else
      # Toon het formulier.
      @render_form = true
      @article_categories = Spree::ArticleCategory.all

      render :action => :index
    end
  end

  def destroy
    @article_category = Spree::ArticleCategory.find(params[:id])
    @article_category.destroy
    @article_categories = Spree::ArticleCategory.all

    flash.now[:notice] = t('admin.article_categories.form.deleted')
  end
end

app/controllers/spree/admin/articles_controller.rb
class Spree::Admin::ArticlesController < Spree::Admin::ResourceController

  def index
    @articles = Spree::Article.all
  end

  def new
    @article = Spree::Article.new
    initialize_lists
  end

  def edit
    @article = Spree::Article.find(params[:id])
    initialize_lists
  end

  def create
    @article = Spree::Article.new(params[:article])

    if @article.save
      redirect_to(admin_articles_url)
    else
      initialize_lists
      render :action => "new"
    end
  end

  def update
    @article = Spree::Article.find(params[:id])

    if @article.update_attributes(params[:article])
      redirect_to(admin_articles_url)
    else
      initialize_lists
      render :action => "new"
    end
  end

  def destroy
    @article = Spree::Article.find(params[:id])
    @article.destroy

    redirect_to(admin_articles_url)
  end


  private

  def initialize_lists
    @articles = Spree::Article.all
    @article_categories = Spree::ArticleCategory.all
    @languages = Language::ALL_LANGUAGES
    @products = Spree::Product.where(:is_printer => true)
  end
end

app/controllers/spree/articles_controller.rb
class Spree::ArticlesController < Spree::BaseController

  def index
    @article_categories = Spree::ArticleCategory.all
    @printers = Spree::Product.where(:is_printer => true)
  end
end

app/views/spree/admin/article_categories/_article_categories.html.erb
<table class="index">
  <tr>
    <th><%= t('activerecord.attributes.article_category.name') %></th>
    <th class="tc"><%= t('scaffold.actions') %></th>
  </tr>
  <% @article_categories.each do |article_category| %>
    <tr>
      <td><%= article_category.name %></td>
      <td class="actions">
        <%= link_to_edit article_category, :class => "edit" %>
        <%= link_to_delete article_category %>
      </td>
    </tr>
  <% end %>
</table>

app/views/spree/admin/article_categories/_form.html.erb
<%= form_for([:admin, @article_category], :html => {:id => "article_category_form", :multipart => true}) do |f| %>
  <fieldset>
    <%= f.label :name %><span class="required">*</span><br />
    <%= f.text_field :name, :class => "fullwidth title" %>
    <%= f.error_message_on :name %>

    <div class="clearfix" data-hook="new_product_attrs">
      <div class="left">

      <%= f.label :icon %><span class="required">*</span>
      <%= f.file_field :icon %>
      <%= f.error_message_on :icon %>

      </div>
    </div>

    <%= render :partial => 'spree/admin/shared/new_resource_links' %>

  </fieldset>
<% end %>

app/views/spree/admin/article_categories/destroy.js.erb
$("#article_categories").html("<%= escape_javascript(render("article_categories"))%>");
$("#flash_notice").html("<%= flash[:notice] %>")
$("#flash_notice_column").show('blind', {}, 300);

/* Hide the form. */
$("#form-column").hide('blind', {}, 300);
$("#article_category-form").html("");

app/views/spree/admin/article_categories/edit.html.erb
<div class="clear"></div>

<%= render :partial => "form" %>

<div class="clear"></div>

app/views/spree/admin/article_categories/edit.js.erb
$("#form").html("<%= escape_javascript(render("form"))%>");
$("#form-column").show(300);
$("#form_title").html("<%= t('admin.article_categories.index.edit') %>");

app/views/spree/admin/article_categories/index.html.erb
<%= render :partial => 'spree/admin/shared/article_sub_menu' %>

<div class="toolbar">
  <ul class="actions">
    <li id="new_article_category_link">
      <%= button_link_to 'New article category', new_admin_article_category_path, {:remote => true, :icon => 'add', :id => 'admin_new_article_category'} %>
    </li>
  </ul>
  <br class="clear" />
</div>

<h1><%= t('.listing') %></h1>

<div id="new_article_category"></div>

<%= render "article_categories" %>

app/views/spree/admin/article_categories/new.html.erb
<%= render :partial => 'spree/admin/shared/article_sub_menu' %>

<%= render :partial => 'form' %>

app/views/spree/admin/article_categories/new.js.erb
$("#new_article_category").html('<%= escape_javascript(render :partial => "form") %>');

app/views/spree/admin/article_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @article_category.name %>
</p>


<%= link_to 'Edit', edit_article_category_path(@article_category) %> |
<%= link_to 'Back', article_categories_path %>

app/views/spree/admin/articles/_articles.html.erb
<div data-hook="toolbar" class="toolbar">
  <ul class="actions">
    <li id="new_product_link">
      <%= button_link_to "New article", new_admin_article_path, {:remote => true, :icon => 'add', :id => 'admin_new_article'} %>
    </li>
  </ul>
  <br class="clear">
</div>

<h1>Listing articles</h1>

<div id="new_article"></div>

<table class="index">
  <tr>
    <th><%= t('activerecord.attributes.article.name') %></th>
    <th><%= t('activerecord.attributes.article_category.name') %></th>
    <th><%= t('activerecord.attributes.article.products') %></th>
    <th class="tc"><%= t('scaffold.actions') %></th>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.name %></td>
      <td><%= article.article_category.name %></td>
      <td>
        <% article.products.each do |product| %>
        <span><%= product.name %>, </span>
        <% end %>
      </td>
      <td class="actions">
        <%= link_to_edit article, :class => "edit" %>
        <%= link_to_delete article %>
      </td>
    </tr>
  <% end %>
</table>

app/views/spree/admin/articles/_form.html.erb
<%= form_for([:admin, @article], :html => {:id => "article_form"}) do |f| %>
  <fieldset>
    <%= f.label :name %><span class="required">*</span><br />
    <%= f.text_field :name, :class => "title" %>
    <%= f.error_message_on :name %>

    <br />

    <%= f.label :content %><span class="required">*</span><br />
    <%= f.text_area :content, :class => 'fullwidth' %>
    <%= f.error_message_on :content %>


    <div class="clearfix" data-hook="new_product_attrs">
      <div class="left">

        <%= f.label :article_category_id %><span class="required">*</span><br />
        <%= f.select :article_category_id, @article_categories.collect {|category| [category.name, category.id]} %>
        <%= f.error_message_on :article_category_id %>

        <br/>

        <%= f.label :language_id %><span class="required">*</span><br />
        <%= f.select :language_id, @languages.collect {|language| [language[:name], language[:id]]} %>
        <%= f.error_message_on :language_id %>

      </div>
      <div class="right">

        <%= f.label :products %><span class="required">*</span><br />
        <% @products.each do |product| -%>
          <%= check_box_tag "article[product_ids][]", product.id, @article.is_relevant_for_product?(product), :id => "article_product_id_#{product.id}" -%> <%= f.label "product_id_#{product.id}", product.name -%><br />
        <% end -%>
        <%= f.error_message_on :products %>

      </div>
    </div>

    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/articles/edit.html.erb
<div class="clear"></div>

<%= render :partial => "form" %>

<div class="clear"></div>

app/views/spree/admin/articles/index.html.erb
<%= render :partial => 'spree/admin/shared/article_sub_menu' %>

<%= render :partial => "articles" %>

app/views/spree/admin/articles/new.html.erb
<%= render :partial => 'spree/admin/shared/article_sub_menu' %>

<%= render :partial => 'form' %>

app/views/spree/admin/articles/new.js.erb
$("#new_article").html('<%= escape_javascript(render :partial => "form") %>');
$("#admin_new_article").parent().hide();

app/views/spree/admin/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @admin_article.name %>
</p>

<p>
  <b>Language:</b>
  <%= @admin_article.language_id %>
</p>


<%= link_to 'Edit', edit_admin_article_path(@admin_article) %> |
<%= link_to 'Back', admin_articles_path %>

app/views/spree/admin/shared/_article_sub_menu.html.erb
<% content_for :sub_menu do %>
  <ul id="sub_nav">
    <%= tab :articles, :url => admin_articles_path %>
    <%= tab :article_categories, :url => admin_article_categories_path %>
  </ul>
<% end %>

app/views/spree/articles/index.html.erb
<div id="articles">
  <div id="select-articles" class="left">
    <%- @printers.each do |printer| %>
      <%= link_to printer.name, "#", :class => "printer-#{printer.id}", :style => ("background-image:url('#{printer.images.first.attachment.url(:mini)}')" if printer.images.any?) %><br />
    <%- end %>
  </div>

  <div class="right" id="show-articles">
    <%- @article_categories.each do |category| %>
      <div class="show-category-<%= category.id %>" style="display:none;">
        <h2><%= category.name %></h2>
        <br />
        <%- category.articles.each do |article| %>
          <%= link_to article.name, article.url %><br />
        <%- end %>
      </div>
    <%- end %>

    <%- @printers.each do |printer| %>
      <div class="show-printer-<%= printer.id %>" style="display:none;">
        <h2><%= printer.name %></h2>
        <br />
        <%- @article_categories.each do |category| %>
          <h3 style="background-image:url('<%= category.icon.url(:mini) %>')"><%= category.name %></h3>
          <% category.articles.each do |article| %>
            <%= link_to article.name, article.url if printer.articles.map(&:id).include? article.id  %><br />
          <% end %>
        <% end %>
      </div>
    <%- end %>
  </div>
</div>

<script type="text/javascript">
  $('#select-articles a').click(function() {
    $('#show-articles').children().hide();
    $('.show-' + $(this).attr('class')).show();
  });
</script>